name: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t anthonylionetti/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true anthonylionetti/react-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Docker-Frontend 
          environment_name: Docker-Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-2-767398024231
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
