name: Deploy Frontend
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrect.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t anthonylionetti/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true anthonylionetti/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      -name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
